const data=[
    {
        name:'Abul Hossain',
        gender:'Male',
        specialties:'Cardiologist',
        country:'Bangladesh',
        age:30,
        salary:'$5000',
        email:'abul45@gmail.com',
        picture:'https://ibb.co/smSLngy',
    },
    {
        name:'Monira Sultana',
        gender:'Female',
        specialties:'Dermatologist',
        country:'Bangladesh',
        age:45,
        salary:'$6000',
        email:'monira22@gmail.com',
        picture:'https://ibb.co/55W645k',
    },
    {
        name:'Kamal Ahmed',
        gender:'Male',
        specialties:'ENT',
        country:'Bangladesh',
        age:35,
        salary:'$5000',
        email:'ahmedkamal@gmail.com',
        picture:'https://ibb.co/rwzFJNw',
    },
    {
        name:'Sagor Chowdhury',
        gender:'Male',
        specialties:'ENT',
        country:'Bngladesh',
        age:30,
        salary:'$4000',
        email:'sagar100@gmail.com',
        picture:'https://ibb.co/LSRQy9D',
    },
    {
        name:'Lotif Chowdhury',
        gender:'Male',
        specialties:'Psychiatrist',
        country:'Bangladesh',
        age:33,
        salary:'$5000',
        email:'lotif12@gmail.com',
        picture:'https://ibb.co/WHX2ccL',
    },
    {
        name:'Fatema Jahan',
        gender:'Female',
        specialties:'Neurologist',
        country:'Bangladesh',
        age:28,
        salary:'$4000',
        email:'fatema992@gmail.com',
        picture:'https://ibb.co/YXyYYX1',
    },
    {
        name:'Mustofa Ahmed',
        gender:'Male',
        specialties:' Cardiologist',
        country:'Bangladesh',
        age:28,
        salary:'$4000',
        email:'fatema992@gmail.com',
        picture:'https://ibb.co/H42wXZ4',
    },
    {
        name:'Jamal Hossain',
        gender:'Male',
        specialties:' Cardiologist',
        country:'Bangladesh',
        age:'40',
        salary:'$5500',
        email:'mustofa100@gmail.com',
        picture:'https://ibb.co/H42wXZ4',
    },
    {
        name:'Sakib Ahmed',
        gender:'Male',
        specialties:' Neurologist',
        country:'Bangladesh',
        age:'38',
        salary:'$5500',
        email:'sakib.22@gmail.com',
        picture:'https://ibb.co/H42wXZ4',
    },
    {
        name:'Shakhawat Ali',
        gender:'Male',
        specialties:' Gastroenterologist',
        country:'Bangladesh',
        age:'50',
        salary:'$6500',
        email:'shakhawat.22@gmail.com',
        picture:'https://ibb.co/QCjvnhC',
    }
]